### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by kingkadienm** [chinaltz/FlutterDemo#1]
有个问题
setBinding(new Binding([gradle: this]))                                 // new
evaluate(new File(                                                      // new
        settingsDir.parentFile,                                               // new
        'my_flutter/.android/include_flutter.groovy'                          // new
))
在这里一直报错，想知道导那个Binding，所有的依赖我都试了，发现都不行，然后把你的demo也下载了，也是在这报错了，我想知道是什么原因？？？求告知

**Comment by chinaltz** [comment]
flutter 环境是否正常 新建Flutter应用是否可运行

**Comment by kingkadienm** [comment]
flutter 一切都正常 这是在原生里嵌套flutter是不行的
![image](https://user-images.githubusercontent.com/25675286/52837880-93878e00-312b-11e9-9c5b-89f7e0d295ae.png)
我按照官方wiki来也是，不清楚是那个配置没有配置

**Comment by ameryzhu** [comment]
我也不行

**Comment by chinaltz** [comment]
我刚下载来看了一下.  这两个文件夹分开导入
![图片](https://user-images.githubusercontent.com/11940289/54181934-13aad480-44db-11e9-9ea0-a8da304c1a7f.png)

flutter_test_module 先运行
![图片](https://user-images.githubusercontent.com/11940289/54182099-8025d380-44db-11e9-97b2-12fcbb9edf0e.png)
或者 在终端 输入 flutter packages get

程序不报错后

![图片](https://user-images.githubusercontent.com/11940289/54182200-c4b16f00-44db-11e9-9f41-01f3e4fd2f91.png)
目录中出现 android 及IOS环境
点击运行 .


打开 FlutterTest

点击运行.

**Comment by l114624915** [comment]
setBinding(new Binding([gradle: this])) // new
evaluate(new File( // new
settingsDir.parentFile, // new
'my_flutter/.android/include_flutter.groovy' // new
))
----还是报错，请问怎么解决？

**Comment by chinaltz** [comment]
> 
> 
> setBinding(new Binding([gradle: this])) // new
> evaluate(new File( // new
> settingsDir.parentFile, // new
> 'my_flutter/.android/include_flutter.groovy' // new
> ))
> ----还是报错，请问怎么解决？

flutter_moudle 是否已经成功运行 可编译

**Comment by l114624915** [comment]
可以了，谢谢Q
